# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = 2



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false

    config.vm.define "vagrant1" do |vagrant1|
        config.vm.box = "ubuntu/trusty64"
        config.vm.network "forwarded_port", guest:80, host:8080
        config.vm.network "forwarded_port", guest:443, host:8443
    end
    config.vm.define "vagrant2" do |vagrant2|
        config.vm.box = "ubuntu/trusty64"
        config.vm.network "forwarded_port", guest:80, host:8080
        config.vm.network "forwarded_port", guest:443, host:8443
    end
    config.vm.define "vagrant3" do |vagrant3|
        config.vm.box = "ubuntu/trusty64"
        config.vm.network "forwarded_port", guest:80, host:8080
        config.vm.network "forwarded_port", guest:443, host:8443
    end
end